[build]
  base = "frontend/"
  publish = "build/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://powerbank-investment.onrender.com"
  REACT_APP_SUPABASE_URL = "https://lbyoclibrlczuiolihza.supabase.co"
  REACT_APP_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxieW9jbGlicmxjenVpb2xpaHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODMyMDAsImV4cCI6MjA3MTQ1OTIwMH0.XX9Zbmb_ZbFKDLXtCkQv6PG3REI3FXcxtEj3ENfqijs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_API_URL = "Backend API URL"